CREATE TABLE noteful_note (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    content TEXT NOT NULL,
    folder_id INTEGER REFERENCES noteful_folder(id),
    modified TIMESTAMP DEFAULT now()
)