CREATE TABLE noteful_note (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    modified TIMESTAMP DEFAULT now(),
    folder_id INTEGER REFERENCES noteful_folder(id),
    content  TEXT NOT NULL
);